name: stocker
description: A modern B2B delivery platform for South African businesses.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_riverpod: ^2.3.6
  go_router: ^10.0.0
  dio: ^5.3.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  intl: ^0.18.1
  flutter_animate: ^4.2.0
  phosphor_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/